import { CustomerData } from "../types"

export var data1 = [
    1,2,3,4
]

export var dataCustomers: Array<CustomerData> = [{
    "id": 1,
    "first_name": "Maurizio",
    "last_name": "Backhouse",
    "email": "mbackhouse0@tripod.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 2,
    "first_name": "Lettie",
    "last_name": "Coch",
    "email": "lcoch1@elpais.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 3,
    "first_name": "Davita",
    "last_name": "Brooker",
    "email": "dbrooker2@privacy.gov.au",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 4,
    "first_name": "Ricoriki",
    "last_name": "Aiston",
    "email": "raiston3@dedecms.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 5,
    "first_name": "Layne",
    "last_name": "Stubbe",
    "email": "lstubbe4@wsj.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 6,
    "first_name": "Ranna",
    "last_name": "Morales",
    "email": "rmorales5@marriott.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 7,
    "first_name": "Fionna",
    "last_name": "Olliff",
    "email": "folliff6@auda.org.au",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 8,
    "first_name": "Florida",
    "last_name": "Andrich",
    "email": "fandrich7@flavors.me",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 9,
    "first_name": "Terra",
    "last_name": "Cribbin",
    "email": "tcribbin8@illinois.edu",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 10,
    "first_name": "Virginia",
    "last_name": "Athridge",
    "email": "vathridge9@oaic.gov.au",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 11,
    "first_name": "Sydel",
    "last_name": "Enrigo",
    "email": "senrigoa@nih.gov",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 12,
    "first_name": "Noll",
    "last_name": "Dimanche",
    "email": "ndimancheb@newyorker.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
    
  }, {
    "id": 13,
    "first_name": "Antonietta",
    "last_name": "Coppins",
    "email": "acoppinsc@elpais.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 14,
    "first_name": "Lizette",
    "last_name": "Siberry",
    "email": "lsiberryd@yale.edu",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 15,
    "first_name": "Garfield",
    "last_name": "Alabastar",
    "email": "galabastare@typepad.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "123456789",
  }, {
    "id": 16,
    "first_name": "David",
    "last_name": "Maldonado",
    "email": "admin@gmail.com",
    "code":"202200176",
    "gener": "masculino",
    "facultad": "Ingenieria",
    "carrera": "Ciencias y Sistemas",
    "password": "12345",
  }]